import type { SkillNode } from "./types";

export const TECH_SKILL_GRAPH: Record<string, SkillNode> = {
  HTML: {
    name: "HTML",
    prerequisites: [],
    unlocks: ["CSS", "JavaScript", "React"],
    usedInCareers: [
      "Frontend Developer",
      "Full Stack Developer",
      "UX Designer",
      "Mobile Developer",
    ],
    difficulty: "Beginner",
    timeEstimate: "1–2 Weeks",
    commonMistakes: [
      "Using non-semantic <div> tags everywhere instead of <header>, <nav>, <main>, <article>, and <footer>.",
      "Neglecting alternative text (alt tags) and form input labels, which breaks accessibility for screen readers.",
    ],
    relatedTechnologies: ["WAI-ARIA", "JSX", "Semantic Web"],
  },
  CSS: {
    name: "CSS & Tailwind",
    prerequisites: ["HTML"],
    unlocks: ["Tailwind CSS", "React UI", "Design Systems"],
    usedInCareers: ["Frontend Developer", "Full Stack Developer", "Mobile Developer"],
    difficulty: "Beginner",
    timeEstimate: "2–4 Weeks",
    commonMistakes: [
      "Overusing absolute positioning instead of modern Flexbox and CSS Grid.",
      "Writing duplicate static styles instead of modular tokens or utility classes.",
    ],
    relatedTechnologies: ["Tailwind CSS", "Flexbox", "CSS Grid", "PostCSS"],
  },
  JavaScript: {
    name: "JavaScript (ES6+)",
    prerequisites: ["HTML"],
    unlocks: ["TypeScript", "React", "Node.js"],
    usedInCareers: [
      "Frontend Developer",
      "Backend Developer",
      "Full Stack Developer",
      "Mobile Developer",
      "QA Automation Engineer",
    ],
    difficulty: "Intermediate",
    timeEstimate: "4–8 Weeks",
    commonMistakes: [
      "Failing to understand the asynchronous event loop, promises, and async/await mechanics.",
      "Mutating state directly rather than using immutable patterns.",
    ],
    relatedTechnologies: ["TypeScript", "Node.js", "Web APIs"],
  },
  TypeScript: {
    name: "TypeScript",
    prerequisites: ["JavaScript"],
    unlocks: ["Enterprise React", "Typed Backend APIs", "Large Scale Systems"],
    usedInCareers: [
      "Frontend Developer",
      "Backend Developer",
      "Full Stack Developer",
      "AI Engineer",
    ],
    difficulty: "Intermediate",
    timeEstimate: "3–5 Weeks",
    commonMistakes: [
      "Typing unknown objects as 'any' instead of 'unknown' or strict generics, defeating type safety.",
      "Over-complicating types with complex conditional mapped types when simple interfaces suffice.",
    ],
    relatedTechnologies: ["React", "Node.js", "Zod", "Prisma"],
  },
  React: {
    name: "React & Next.js",
    prerequisites: ["JavaScript", "HTML", "CSS"],
    unlocks: ["Next.js", "Full Stack Web Apps", "React Native"],
    usedInCareers: ["Frontend Developer", "Full Stack Developer", "Mobile Developer"],
    difficulty: "Intermediate",
    timeEstimate: "6–10 Weeks",
    commonMistakes: [
      "Creating infinite re-render loops in useEffect by omitting or misconfiguring dependency arrays.",
      "Prop-drilling deep state instead of using context or lightweight stores like Zustand.",
    ],
    relatedTechnologies: ["Next.js", "TanStack Router", "TanStack Query", "Zustand"],
  },
  "Node.js": {
    name: "Node.js & Express",
    prerequisites: ["JavaScript"],
    unlocks: ["Backend Microservices", "Full Stack Apps", "CLI Tools"],
    usedInCareers: ["Backend Developer", "Full Stack Developer", "DevOps Engineer"],
    difficulty: "Intermediate",
    timeEstimate: "4–6 Weeks",
    commonMistakes: [
      "Blocking the single-threaded event loop with expensive synchronous CPU computations.",
      "Failing to catch asynchronous promise errors, causing unhandled process crashes.",
    ],
    relatedTechnologies: ["Express", "FastAPI", "Hono", "REST APIs"],
  },
  "SQL & PostgreSQL": {
    name: "SQL & PostgreSQL",
    prerequisites: [],
    unlocks: ["Data Modeling", "ORMs (Prisma/Drizzle)", "Data Analytics"],
    usedInCareers: ["Backend Developer", "Full Stack Developer", "Data Scientist", "AI Engineer"],
    difficulty: "Intermediate",
    timeEstimate: "4–6 Weeks",
    commonMistakes: [
      "Failing to add database indexes on foreign keys and search columns, resulting in full table scans.",
      "Suffering from N+1 query patterns in backend ORM loops.",
    ],
    relatedTechnologies: ["PostgreSQL", "Prisma", "Drizzle ORM", "pgvector"],
  },
  Docker: {
    name: "Docker & Containers",
    prerequisites: ["Linux"],
    unlocks: ["Kubernetes", "CI/CD Pipelines", "Microservices"],
    usedInCareers: [
      "DevOps Engineer",
      "Cloud Engineer",
      "Backend Developer",
      "Full Stack Developer",
    ],
    difficulty: "Intermediate",
    timeEstimate: "3–5 Weeks",
    commonMistakes: [
      "Running containerized processes as root user in production environments.",
      "Failing to utilize multi-stage builds, shipping 1GB+ bloated container images.",
    ],
    relatedTechnologies: ["Docker Compose", "Kubernetes", "Container Registries"],
  },
  Kubernetes: {
    name: "Kubernetes (K8s)",
    prerequisites: ["Docker", "Linux"],
    unlocks: ["Cloud Orchestration", "Platform Engineering", "SRE"],
    usedInCareers: ["DevOps Engineer", "Cloud Engineer"],
    difficulty: "Advanced",
    timeEstimate: "8–12 Weeks",
    commonMistakes: [
      "Omitting CPU and memory resource requests/limits, leading to node resource starvation.",
      "Failing to define liveness and readiness probes, causing broken traffic routing to dead pods.",
    ],
    relatedTechnologies: ["Helm", "ArgoCD", "Prometheus", "Service Mesh"],
  },
  "AWS Cloud": {
    name: "AWS Cloud Infrastructure",
    prerequisites: ["Linux", "Networking"],
    unlocks: ["Cloud Architecture", "Serverless", "Terraform IaC"],
    usedInCareers: ["Cloud Engineer", "DevOps Engineer", "Backend Developer"],
    difficulty: "Intermediate",
    timeEstimate: "6–10 Weeks",
    commonMistakes: [
      "Attaching broad AdministratorAccess to IAM roles used by application services.",
      "Leaving storage buckets publicly readable to the world without encryption.",
    ],
    relatedTechnologies: ["EC2", "S3", "RDS", "Lambda", "Terraform"],
  },
  Python: {
    name: "Python",
    prerequisites: [],
    unlocks: ["Machine Learning", "Data Science", "Backend (FastAPI)", "AI Engineering"],
    usedInCareers: ["AI Engineer", "Data Scientist", "Backend Developer", "Cybersecurity Analyst"],
    difficulty: "Beginner",
    timeEstimate: "4–6 Weeks",
    commonMistakes: [
      "Using inefficient for-loops instead of vectorized operations in NumPy and Pandas.",
      "Polluting global environments instead of using virtual environments (venv/conda).",
    ],
    relatedTechnologies: ["FastAPI", "NumPy", "Pandas", "PyTorch"],
  },
  "Generative AI & LLMs": {
    name: "Generative AI & RAG",
    prerequisites: ["Python", "SQL & PostgreSQL"],
    unlocks: ["AI Engineering", "Autonomous Agents", "Vector Search"],
    usedInCareers: ["AI Engineer", "Data Scientist", "Full Stack Developer"],
    difficulty: "Intermediate",
    timeEstimate: "6–8 Weeks",
    commonMistakes: [
      "Relying on arbitrary chunk sizes that split paragraphs mid-sentence, destroying semantic context.",
      "Failing to validate model JSON outputs with schemas, leading to runtime UI crashes.",
    ],
    relatedTechnologies: ["Google Gemini API", "pgvector", "LangChain", "LlamaIndex"],
  },
};
